# During the github workflow to auto deploy the app
# This config file will be used to overwrite the config.yml in the schematic folder
#
# Please modify the configuration values based on your project

# Do not change the 'definitions' section unless you know what you're doing
definitions:
  synapse_config: '.synapseConfig'
  creds_path: 'credentials.json'
  token_pickle: 'token.pickle'
  service_acct_creds: 'schematic_service_account_creds.json'

synapse:
  master_fileview: 'syn20446927' # fileview of project with datasets on Synapse
  manifest_folder: 'manifests' # manifests will be downloaded to this folder
  manifest_filename: 'synapse_storage_manifest.csv' # name of the manifest file in the project dataset
  token_creds: 'syn23643259' # synapse ID of credentials.json file
  service_acct_creds: 'syn25171627' # synapse ID of service_account_creds.json file

manifest:
  title: 'Patient Manifest' # title of metadata manifest file
  data_type: 'Patient' # component or data type from the data model

model:
  input:
    download_url: 'https://raw.githubusercontent.com/ncihtan/data-models/main/HTAN.model.jsonld' # url to download JSON-LD data model
    location: 'data-models/HTAN.model.jsonld' # path to JSON-LD data model
    file_type: 'local' # only type "local" is supported currently

style:
  google_manifest:
    req_bg_color:
      red: 0.9215
      green: 0.9725
      blue: 0.9803
    opt_bg_color:
      red: 1.0
      green: 1.0
      blue: 0.9019
    master_template_id: '1LYS5qE4nV9jzcYw5sXwCza25slDfRA1CIg3cs-hCdpU'
    strict_validation: true
