# Do not change the 'definitions' section unless you know what you're doing
definitions:
  synapse_config: ".synapseConfig"
  creds_path: "credentials.json"
  token_pickle: "token.pickle"
  service_acct_creds: "schematic_service_account_creds.json"

synapse:
  master_fileview: 'syn23643253'
  manifest_folder: 'manifests'
  manifest_basename: 'synapse_storage_manifest'
  token_creds: 'syn23643259'
  service_acct_creds: 'syn25171627'

manifest:
  title: 'example' # if making many manifests, just include name prefix
  data_type:  # to make all manifests enter only 'all manifests'
    - 'Biospecimen'
    - 'Patient'

model:
  input:
    repo: 'Sage-Bionetworks/data-models' # repo of data model: {repo_owner}/{repo_name}
    location: 'data-models/example.model.jsonld' # path to JSON-LD data mode from root
    file_type: 'local'

app:
  oauth:
    client_id: '100126'
    client_secrets: 'vw34nFSl1fpGaBC1iqpIuPxCnOg5xf99DC9FwWxqCOQ'
    url:  'http://127.0.0.1:8100'
  versions:
    app_version: "v22.03.01",
    service_version: "v0.1.0",
    schema_version: "v0.1.0"

style:
  google_manifest:
    req_bg_color:
      red: 0.9215
      green: 0.9725
      blue: 0.9803
    opt_bg_color:
      red: 1.0
      green: 1.0
      blue: 0.9019
    master_template_id: '1LYS5qE4nV9jzcYw5sXwCza25slDfRA1CIg3cs-hCdpU'
    strict_validation: true
