definitions:
    synapse_config: "~/path/to/.synapseConfig"
    creds_path: "~/path/to/credentials.json"
    token_pickle: "~/path/to/token.pickle"
    service_acct_creds: "~/path/to/service_account_creds.json"

synapse:
    master_fileview: "syn23643253" # fileview of project with datasets on Synapse
    manifest_folder: "~/path/to/manifest_folder/" # manifests will be downloaded to this folder
    manifest_filename: "filename.ext" # name of the manifest file in the project dataset
    token_creds: "syn23643259" # synapse ID of credentials.json file
    service_acct_creds: "syn25171627" # synapse ID of service_account_creds.json file

manifest:
    title: "Patient Manifest " # title of metadata manifest file
    data_type: 
      - "Patient" # component or data type from the data model

model:
    input:
        location: "data/schema_org_schemas/example.jsonld" # path to JSON-LD data model
        file_type: "local" # only type "local" is supported currently
