# Do not change the 'definitions' section unless you know what you're doing
definitions:
  synapse_config: '.synapseConfig'
  creds_path: 'credentials.json'
  token_pickle: 'token.pickle'
  service_acct_creds: 'schematic_service_account_creds.json'

synapse:
  master_fileview: 'syn36759435'
  manifest_folder: 'manifests'
  manifest_basename: 'synapse_storage_manifest'
  token_creds: 'syn23643259'
  service_acct_creds: 'syn25171627'

manifest:
  # if making many manifests, just include name prefix
  title: 'example'
  # to make all manifests enter only 'all manifests'
  data_type:
    - 'Biospecimen'
    - 'Patient'

model:
  input:
    # if both 'download_url' and 'repo' present, `repo` will be used
    download_url: 'https://raw.githubusercontent.com/Sage-Bionetworks/sysbioDCCjsonschemas/model-ad-test-schema/schematic_schemas/model-ad-test/model-ad-schematic-test-schema-v1.jsonld' # url to download JSON-LD data model
    repo: 'Sage-Bionetworks/sysbioDCCjsonschemas' # data model repo url (<repo-owner>/<repo-name>/<version/branch>), version or branch is optional
    location: 'tree/model-ad-test-schema/schematic_schemas/model-ad-test' # path to JSON-LD file
    file_type: 'local'

style:
  google_manifest:
    req_bg_color:
      red: 0.9215
      green: 0.9725
      blue: 0.9803
    opt_bg_color:
      red: 1.0
      green: 1.0
      blue: 0.9019
    master_template_id: '1LYS5qE4nV9jzcYw5sXwCza25slDfRA1CIg3cs-hCdpU'
    strict_validation: true
