# Do not change the 'definitions' section unless you know what you're doing
definitions:
  synapse_config: '.synapseConfig'
  creds_path: 'credentials.json'
  token_pickle: 'token.pickle'
  service_acct_creds: 'schematic_service_account_creds.json'

synapse:
  master_fileview: 'syn16858331'
  manifest_folder: 'manifests'
  manifest_basename: 'synapse_storage_manifest' 
  token_creds: 'syn21088684'
  service_acct_creds: 'syn25171627'
  
manifest:
  title: 'NF'
  data_type: 
    - 'NF'

model:
  input:
    download_url: 'https://raw.githubusercontent.com/nf-osi/nf-metadata-dictionary/32dc54f67d67955c5d75a4ef4ce9cb25781af254/NF.jsonld' # url to download JSON-LD data model
    location: 'data-models/NF.jsonld' # path to JSON-LD data model
    file_type: 'local' 
    
style:
  google_manifest:
    req_bg_color:
      red: 0.9215
      green: 0.9725
      blue: 0.9803
    opt_bg_color:
      red: 1.0
      green: 1.0
      blue: 0.9019
    master_template_id: '1LYS5qE4nV9jzcYw5sXwCza25slDfRA1CIg3cs-hCdpU'
    strict_validation: false
