# Auto open PR
name: auto-open-pr
on:
  repository_dispatch:
    types: trigger-frontend
  workflow_dispatch:
jobs:
  auto-open-pr:
    runs-on: ubuntu-latest
    steps:        
      - name: Check out repository
        uses: actions/checkout@v3

      - name: create the branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: 'develop-update-schematic'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit sha, release tag, and branch name
        run: |
          echo 'COMMIT_REF=${{ github.event.client_payload.commit-sha }}' >> $GITHUB_ENV
          echo 'RELEASE_VERSION=${{ github.event.client_payload.release-version }}' >> $GITHUB_ENV
          echo 'DEFAULT_VAL='empty'' >> $GITHUB_ENV

      #### create different pull request based on if release tag exists. 
      ## when a new release is available
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          valueFile: schematic_config.yml
          branch: develop-update-schematic
          targetBranch: develop
          createPR: true
          labels: 'auto-PR'
          title: 'Version Updates triggered by schematic'
          description: Triggered by schematic updates 
          message: 'Triggered by schematic updates'
          changes: |
            {
              "schematic.branch": "${{ env.BRANCH_NAME|| env.DEFAULT_VAL }}",
              "schematic.sha": "${{ env.COMMMIT_REF || env.DEFAULT_VAL }}",
              "schematic.release_version": "${{ env.RELEASE_VERSION || env.DEFAULT_VAL}}"
            }